packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  esbuild: false
  sharp: false
  workerd: false

ignoredBuiltDependencies:
  - esbuild
  - sharp
  - workerd

minimumReleaseAgeExclude:
  - '@vercel/sandbox@2.7.0'
