import assert from "node:assert/strict";
let listener;
const chromeElement = { attributes: { style: "color: red; display: block;" }, getAttribute(name) { return this.attributes[name] ?? null; }, setAttribute(name, value) { this.attributes[name] = value; }, removeAttribute(name) { delete this.attributes[name]; }, style: { setProperty(_name, value) { this.owner.setAttribute("style", `visibility: ${value};`); } } };
chromeElement.style.owner = chromeElement;
globalThis.HTMLElement = class HTMLElement {};
Object.setPrototypeOf(chromeElement, HTMLElement.prototype);
globalThis.window = { addEventListener() {}, innerWidth: 100, innerHeight: 80, devicePixelRatio: 1 };
globalThis.location = { origin: "http://host.test", pathname: "/booking" };
globalThis.document = { querySelectorAll(selector) { return selector === "[data-sonik-capture-chrome]" ? [chromeElement] : []; }, createElement() { return { style: {}, remove() {} }; }, documentElement: { append() {} } };
globalThis.chrome = { runtime: { onMessage: { addListener(fn) { listener = fn; } }, sendMessage() {} } };
await import(`../dist/content-script.js?chrome=${crypto.randomUUID()}`);
listener({ type: "initialize", version: "sonik.active-tab.v1", nonce: "n", tabId: 1, windowId: 1 }, null, () => {});
listener({ type: "prepare-capture", version: "sonik.active-tab.v1", nonce: "n" }, null, (value) => assert.deepEqual(value.redactionsApplied, ["Sonik capture chrome"]));
assert.equal(chromeElement.getAttribute("style"), "visibility: hidden;");
listener({ type: "clear-capture", version: "sonik.active-tab.v1", nonce: "n" }, null, () => {});
assert.equal(chromeElement.getAttribute("style"), "color: red; display: block;");
listener({ type: "prepare-capture", version: "sonik.active-tab.v1", nonce: "n" }, null, () => {});
listener({ type: "clear-capture", version: "sonik.active-tab.v1", nonce: "n" }, null, () => {});
assert.equal(chromeElement.getAttribute("style"), "color: red; display: block;");
console.log("dev-workbench extension capture chrome exact restore: ok");
