// Curated demo-seed corpus: hand-authored booking.context.intake records
// (not model-generated) spanning restaurants, golf tee sheets, event venues,
// fitness/yoga studios, hotel/spa, and private dining. Each record supplies a
// venueName, a category, the intakeMode that drives /manifest/intakeMode, and
// a full ANSWERED set of values for every question in
// scripts/harness/lib/intake-spec-builder.mjs's INTAKE_QUESTIONS (no skips —
// this is a "completed intake" demo corpus, not a partial-draft one).
//
// scripts/harness/seed-batch.mjs cycles this corpus (with light name/number
// variation) to reach an arbitrary --count. Names are professional and
// venue-plausible per Dan's taste — no placeholder/"Test 001" naming.

/** @typedef {{ venueName: string, category: string, intakeMode: "venue_schedule"|"event"|"hybrid", answers: Record<string, unknown> }} SeedRecord */

/** @type {SeedRecord[]} */
export const SEED_CORPUS = [
  // --- Restaurants (varied cuisines/service styles) ---
  {
    venueName: "Bella Trattoria",
    category: "restaurant",
    intakeMode: "venue_schedule",
    answers: {
      q_intake_mode: "venue_schedule",
      q_inventory_core: "Dinner reservations for an Italian trattoria, plus a small standing bar for walk-ins without a table booking.",
      q_business_name: "Bella Trattoria",
      q_open_days: ["tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
      q_operating_hours: "Tuesday through Sunday, 5pm to 10pm. Closed Mondays for deep cleaning and prep.",
      q_table_layout: "Tables 1-8 are 2-tops along the front window, 9-16 are 4-tops in the main dining room, 17-19 are 6-top family tables near the kitchen pass.",
      q_service_periods: "Dinner only, 5pm-10pm, with a shortened bar menu available until 11pm on Fridays and Saturdays.",
      q_menu_requirements: ["dinner", "drinks"],
      q_confirmation_mode: "instant_confirm",
    },
  },
  {
    venueName: "Harbor & Vine",
    category: "restaurant",
    intakeMode: "venue_schedule",
    answers: {
      q_intake_mode: "venue_schedule",
      q_inventory_core: "Seafood-focused dinner reservations with a raw bar counter and an outdoor patio for warmer months.",
      q_business_name: "Harbor & Vine",
      q_open_days: ["wednesday", "thursday", "friday", "saturday", "sunday"],
      q_operating_hours: "Wednesday through Sunday, 4:30pm to 9:30pm; patio seating closes at 9pm.",
      q_table_layout: "Raw bar counter seats 10, indoor tables 1-14 are 2-4 tops, patio tables 15-20 are 2-tops weather permitting.",
      q_service_periods: "Dinner service 4:30-9:30, with a happy hour raw bar menu 4:30-6pm.",
      q_menu_requirements: ["dinner", "drinks", "special_event"],
      q_confirmation_mode: "instant_confirm",
    },
  },
  {
    venueName: "Sakura House",
    category: "restaurant",
    intakeMode: "venue_schedule",
    answers: {
      q_intake_mode: "venue_schedule",
      q_inventory_core: "Omakase counter seats and standard table reservations for a Japanese restaurant, sushi and izakaya menus.",
      q_business_name: "Sakura House",
      q_open_days: ["tuesday", "wednesday", "thursday", "friday", "saturday"],
      q_operating_hours: "Tuesday through Saturday, two seatings: 5:30pm and 8:30pm.",
      q_table_layout: "Omakase counter has 8 seats, dining room tables 1-10 are 2-tops, 11-14 are 4-tops.",
      q_service_periods: "Two fixed dinner seatings per night, 5:30pm and 8:30pm; no walk-in lunch service.",
      q_menu_requirements: ["dinner", "drinks"],
      q_confirmation_mode: "deposit_then_confirm",
    },
  },
  {
    venueName: "Casa Verde Cantina",
    category: "restaurant",
    intakeMode: "venue_schedule",
    answers: {
      q_intake_mode: "venue_schedule",
      q_inventory_core: "Casual Mexican dining with lunch and dinner reservations plus a large communal patio for group bookings.",
      q_business_name: "Casa Verde Cantina",
      q_open_days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
      q_operating_hours: "Open daily, 11am to 10pm, with weekend brunch starting at 10am.",
      q_table_layout: "Indoor tables 1-12 are 4-tops, patio tables 13-22 are 4- to 8-tops for groups, plus a 12-seat communal table for large parties.",
      q_service_periods: "Lunch 11-3, dinner 5-10, weekend brunch 10-2 on Saturdays and Sundays.",
      q_menu_requirements: ["lunch", "dinner", "brunch", "drinks"],
      q_confirmation_mode: "instant_confirm",
    },
  },
  {
    venueName: "The Copper Grill",
    category: "restaurant",
    intakeMode: "venue_schedule",
    answers: {
      q_intake_mode: "venue_schedule",
      q_inventory_core: "Steakhouse dinner reservations with private booth seating and a chef's table for special occasions.",
      q_business_name: "The Copper Grill",
      q_open_days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday"],
      q_operating_hours: "Monday through Saturday, 5pm to 11pm. Closed Sundays.",
      q_table_layout: "Main floor tables 1-16 are 2-4 tops, booths 17-20 seat 6, chef's table seats 8 with kitchen view.",
      q_service_periods: "Dinner only, 5pm-11pm, last seating at 9:30pm.",
      q_menu_requirements: ["dinner", "drinks", "special_event"],
      q_confirmation_mode: "manual_approval",
    },
  },
  {
    venueName: "Golden Wok",
    category: "restaurant",
    intakeMode: "venue_schedule",
    answers: {
      q_intake_mode: "venue_schedule",
      q_inventory_core: "Family-style Cantonese dinner reservations, including large round banquet tables for celebrations.",
      q_business_name: "Golden Wok",
      q_open_days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
      q_operating_hours: "Open daily 11:30am to 9:30pm, banquet room available by request until 11pm.",
      q_table_layout: "Standard tables 1-15 seat 4-6, banquet round tables 16-20 seat 10-12 for celebrations.",
      q_service_periods: "Lunch 11:30-2:30, dinner 5-9:30, banquet bookings by request outside standard hours.",
      q_menu_requirements: ["lunch", "dinner", "special_event"],
      q_confirmation_mode: "request_to_book",
    },
  },
  {
    venueName: "Le Petit Bistro",
    category: "restaurant",
    intakeMode: "venue_schedule",
    answers: {
      q_intake_mode: "venue_schedule",
      q_inventory_core: "Intimate French bistro dinner reservations, 40 seats total, no bar seating.",
      q_business_name: "Le Petit Bistro",
      q_open_days: ["wednesday", "thursday", "friday", "saturday"],
      q_operating_hours: "Wednesday through Saturday, 6pm to 9:30pm, single nightly seating window.",
      q_table_layout: "Tables 1-10 are 2-tops, 11-14 are 4-tops; no walk-in seating, reservation only.",
      q_service_periods: "Dinner only, one continuous seating 6pm-9:30pm.",
      q_menu_requirements: ["dinner", "drinks"],
      q_confirmation_mode: "instant_confirm",
    },
  },
  {
    venueName: "Blue Heron Diner",
    category: "restaurant",
    intakeMode: "venue_schedule",
    answers: {
      q_intake_mode: "venue_schedule",
      q_inventory_core: "All-day breakfast and lunch diner with counter seating and booths, mostly walk-in with reservations for groups of 6+.",
      q_business_name: "Blue Heron Diner",
      q_open_days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
      q_operating_hours: "Open daily 6am to 3pm.",
      q_table_layout: "Counter seats 12, booths 1-10 seat 4, large table 11 seats 8 for groups.",
      q_service_periods: "Breakfast 6-11, lunch 11-3, no dinner service.",
      q_menu_requirements: ["breakfast", "lunch"],
      q_confirmation_mode: "request_to_book",
    },
  },
  {
    venueName: "Marlow Rooftop",
    category: "restaurant",
    intakeMode: "hybrid",
    answers: {
      q_intake_mode: "hybrid",
      q_inventory_core: "Rooftop lounge with standard dinner reservations plus bookable VIP cabanas and a private event buyout option.",
      q_business_name: "Marlow Rooftop",
      q_open_days: ["thursday", "friday", "saturday", "sunday"],
      q_operating_hours: "Thursday through Sunday, 4pm to midnight, weather permitting.",
      q_table_layout: "General seating tables 1-20 are 2-4 tops, VIP cabanas A-F seat 8-10 with bottle service.",
      q_service_periods: "Sunset happy hour 4-6pm, dinner 6-10pm, lounge service until midnight.",
      q_menu_requirements: ["dinner", "drinks", "special_event"],
      q_confirmation_mode: "deposit_then_confirm",
    },
  },
  {
    venueName: "Willowbrook Farm Table",
    category: "restaurant",
    intakeMode: "venue_schedule",
    answers: {
      q_intake_mode: "venue_schedule",
      q_inventory_core: "Farm-to-table dinner reservations with a seasonal tasting menu and a private greenhouse dining room.",
      q_business_name: "Willowbrook Farm Table",
      q_open_days: ["thursday", "friday", "saturday"],
      q_operating_hours: "Thursday through Saturday, two seatings at 6pm and 8:30pm.",
      q_table_layout: "Main room tables 1-12 are 2-4 tops, greenhouse room seats 10 for private tasting-menu bookings.",
      q_service_periods: "Fixed tasting-menu seatings only, 6pm and 8:30pm.",
      q_menu_requirements: ["dinner", "drinks"],
      q_confirmation_mode: "deposit_then_confirm",
    },
  },

  // --- Golf tee sheets ---
  {
    venueName: "Pinehurst Tee Sheet",
    category: "golf",
    intakeMode: "venue_schedule",
    answers: {
      q_intake_mode: "venue_schedule",
      q_inventory_core: "18-hole championship course tee times, sold in 8-minute intervals, up to foursomes per slot.",
      q_business_name: "Pinehurst Tee Sheet",
      q_open_days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
      q_operating_hours: "Dawn to dusk daily, first tee time 6:30am, last tee time 5:15pm depending on season.",
      q_table_layout: "Single 18-hole tee sheet, tee times released in 8-minute intervals, max 4 players per slot.",
      q_service_periods: "Morning tee times 6:30-11, afternoon tee times 11-5:15, twilight rate after 3pm.",
      q_menu_requirements: [],
      q_confirmation_mode: "instant_confirm",
    },
  },
  {
    venueName: "Red Rock Golf Club",
    category: "golf",
    intakeMode: "venue_schedule",
    answers: {
      q_intake_mode: "venue_schedule",
      q_inventory_core: "9-hole executive course tee times plus a covered driving range with bookable bays.",
      q_business_name: "Red Rock Golf Club",
      q_open_days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
      q_operating_hours: "Course open 6am to 7pm, driving range open until 9pm with lights.",
      q_table_layout: "9-hole tee sheet in 10-minute intervals, plus 20 driving range bays bookable in 1-hour blocks.",
      q_service_periods: "Course tee times 6am-7pm, range bays 6am-9pm.",
      q_menu_requirements: [],
      q_confirmation_mode: "instant_confirm",
    },
  },
  {
    venueName: "Cypress Point Links",
    category: "golf",
    intakeMode: "hybrid",
    answers: {
      q_intake_mode: "hybrid",
      q_inventory_core: "18-hole coastal links tee times plus a members' clubhouse dining room bookable separately for lunch.",
      q_business_name: "Cypress Point Links",
      q_open_days: ["tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
      q_operating_hours: "Course open 6:45am to 6pm Tuesday-Sunday, closed Mondays for maintenance. Clubhouse dining 11am-3pm.",
      q_table_layout: "18-hole tee sheet in 9-minute intervals; clubhouse dining room tables 1-10 seat 2-6.",
      q_service_periods: "Morning tee times 6:45-11, afternoon 11-6; clubhouse lunch service 11am-3pm.",
      q_menu_requirements: ["lunch"],
      q_confirmation_mode: "manual_approval",
    },
  },
  {
    venueName: "Sandy Bluff Municipal",
    category: "golf",
    intakeMode: "venue_schedule",
    answers: {
      q_intake_mode: "venue_schedule",
      q_inventory_core: "Public 18-hole municipal course tee times, walk-up friendly with online booking for advance slots.",
      q_business_name: "Sandy Bluff Municipal",
      q_open_days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
      q_operating_hours: "Sunrise to sunset daily, seasonal hours posted monthly.",
      q_table_layout: "18-hole tee sheet in 10-minute intervals, up to 4 players per slot, senior and twilight discount windows.",
      q_service_periods: "Standard rate 7am-3pm, twilight rate 3pm-close.",
      q_menu_requirements: [],
      q_confirmation_mode: "instant_confirm",
    },
  },

  // --- Event venues ---
  {
    venueName: "Halcyon Event Hall",
    category: "event_venue",
    intakeMode: "event",
    answers: {
      q_intake_mode: "event",
      q_inventory_core: "Full-building rental for weddings and corporate galas, 300-guest capacity ballroom with adjacent cocktail lounge.",
      q_business_name: "Halcyon Event Hall",
      q_open_days: ["friday", "saturday", "sunday"],
      q_operating_hours: "Bookable Friday through Sunday, standard rental window 10am to midnight.",
      q_table_layout: "Ballroom seats 300 banquet-style or 400 theater-style; cocktail lounge holds 80 standing.",
      q_service_periods: "Single full-day rental window per booking; setup access from 10am, breakdown by midnight.",
      q_menu_requirements: ["special_event", "drinks"],
      q_confirmation_mode: "deposit_then_confirm",
    },
  },
  {
    venueName: "Ironworks Loft",
    category: "event_venue",
    intakeMode: "event",
    answers: {
      q_intake_mode: "event",
      q_inventory_core: "Converted industrial loft for private parties, product launches, and photo shoots, 150-guest capacity.",
      q_business_name: "Ironworks Loft",
      q_open_days: ["thursday", "friday", "saturday", "sunday"],
      q_operating_hours: "Bookable Thursday through Sunday, half-day (4hr) or full-day (10hr) rental blocks.",
      q_table_layout: "Open floor plan, movable furniture for up to 150 standing or 90 seated; freight elevator load-in.",
      q_service_periods: "Half-day rental 9am-1pm or 2pm-6pm; full-day rental 9am-7pm.",
      q_menu_requirements: ["special_event"],
      q_confirmation_mode: "request_to_book",
    },
  },
  {
    venueName: "Meridian Conference Center",
    category: "event_venue",
    intakeMode: "hybrid",
    answers: {
      q_intake_mode: "hybrid",
      q_inventory_core: "Corporate conference center with a main auditorium plus five bookable breakout rooms of varying size.",
      q_business_name: "Meridian Conference Center",
      q_open_days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
      q_operating_hours: "Weekdays 7am to 8pm, weekend access by special arrangement only.",
      q_table_layout: "Main auditorium seats 250 theater-style; breakout rooms A-E seat 12-40 each in boardroom or classroom setup.",
      q_service_periods: "Half-day blocks 7am-1pm and 1pm-8pm, full-day 7am-8pm.",
      q_menu_requirements: ["breakfast", "lunch", "special_event"],
      q_confirmation_mode: "manual_approval",
    },
  },
  {
    venueName: "Willow Creek Barn",
    category: "event_venue",
    intakeMode: "event",
    answers: {
      q_intake_mode: "event",
      q_inventory_core: "Restored barn venue for weddings and rehearsal dinners, indoor hall plus outdoor ceremony lawn.",
      q_business_name: "Willow Creek Barn",
      q_open_days: ["friday", "saturday", "sunday"],
      q_operating_hours: "Seasonal, April through October, Friday through Sunday, 9am to 11pm.",
      q_table_layout: "Barn hall seats 180 banquet-style; ceremony lawn accommodates 200 chairs.",
      q_service_periods: "Full-day rental only, setup 9am, ceremony/reception window flexible, breakdown by 11pm.",
      q_menu_requirements: ["special_event", "drinks"],
      q_confirmation_mode: "deposit_then_confirm",
    },
  },
  {
    venueName: "Northgate Rooftop Terrace",
    category: "event_venue",
    intakeMode: "event",
    answers: {
      q_intake_mode: "event",
      q_inventory_core: "Downtown rooftop terrace for private receptions and mixers, 120-guest standing capacity with skyline views.",
      q_business_name: "Northgate Rooftop Terrace",
      q_open_days: ["wednesday", "thursday", "friday", "saturday"],
      q_operating_hours: "Wednesday through Saturday, 5pm to midnight, weather-dependent with an indoor backup space.",
      q_table_layout: "Open terrace layout, standing capacity 120 or seated reception for 80 with lounge furniture.",
      q_service_periods: "Evening rentals only, 5pm-midnight, minimum 3-hour block.",
      q_menu_requirements: ["drinks", "special_event"],
      q_confirmation_mode: "deposit_then_confirm",
    },
  },

  // --- Fitness / yoga studios ---
  {
    venueName: "Solstice Yoga Studio",
    category: "fitness",
    intakeMode: "venue_schedule",
    answers: {
      q_intake_mode: "venue_schedule",
      q_inventory_core: "Drop-in and class-pass yoga sessions across two studio rooms, including a heated hot-yoga room.",
      q_business_name: "Solstice Yoga Studio",
      q_open_days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
      q_operating_hours: "Classes run daily 6am to 8:30pm, front desk open 5:30am to 9pm.",
      q_table_layout: "Studio A holds 24 mats (unheated), Studio B holds 18 mats (heated to 95F for hot yoga).",
      q_service_periods: "Morning classes 6-9am, midday 11am-1pm, evening 5-8:30pm.",
      q_menu_requirements: [],
      q_confirmation_mode: "instant_confirm",
    },
  },
  {
    venueName: "Ironclad Strength Collective",
    category: "fitness",
    intakeMode: "venue_schedule",
    answers: {
      q_intake_mode: "venue_schedule",
      q_inventory_core: "Small-group strength training sessions and open-gym time slots, capped headcount per session.",
      q_business_name: "Ironclad Strength Collective",
      q_open_days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday"],
      q_operating_hours: "Monday through Friday 5am to 9pm, Saturday 7am to 2pm.",
      q_table_layout: "Main floor supports 12 lifters per coached session; open-gym slots capped at 20 members.",
      q_service_periods: "Coached sessions on the hour 5am-8pm weekdays; open gym all remaining hours.",
      q_menu_requirements: [],
      q_confirmation_mode: "instant_confirm",
    },
  },
  {
    venueName: "Tidewater Pilates Studio",
    category: "fitness",
    intakeMode: "venue_schedule",
    answers: {
      q_intake_mode: "venue_schedule",
      q_inventory_core: "Reformer Pilates classes booked by machine, plus private one-on-one sessions.",
      q_business_name: "Tidewater Pilates Studio",
      q_open_days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday"],
      q_operating_hours: "Monday through Friday 6am to 7pm, Saturday 8am to noon.",
      q_table_layout: "10 reformer machines in the group room, 1 private studio room for one-on-one sessions.",
      q_service_periods: "Group classes on the half-hour, private sessions by appointment.",
      q_menu_requirements: [],
      q_confirmation_mode: "manual_approval",
    },
  },
  {
    venueName: "Basecamp Climbing Gym",
    category: "fitness",
    intakeMode: "hybrid",
    answers: {
      q_intake_mode: "hybrid",
      q_inventory_core: "Day-pass climbing wall access plus bookable belay-certification classes and private coaching sessions.",
      q_business_name: "Basecamp Climbing Gym",
      q_open_days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
      q_operating_hours: "Open daily 7am to 11pm.",
      q_table_layout: "Bouldering area capacity 40 climbers, roped walls capacity 30 climbers, one classroom for certification courses.",
      q_service_periods: "General access all open hours; certification classes scheduled twice weekly.",
      q_menu_requirements: [],
      q_confirmation_mode: "instant_confirm",
    },
  },

  // --- Hotel / spa ---
  {
    venueName: "Aldergate Inn & Spa",
    category: "hotel_spa",
    intakeMode: "hybrid",
    answers: {
      q_intake_mode: "hybrid",
      q_inventory_core: "Boutique inn room bookings plus a separate full-service spa with treatment room reservations.",
      q_business_name: "Aldergate Inn & Spa",
      q_open_days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
      q_operating_hours: "Front desk 24/7; spa treatments booked 9am to 7pm daily.",
      q_table_layout: "18 guest rooms across 3 floors; spa has 4 treatment rooms plus a couples' suite.",
      q_service_periods: "Standard check-in 3pm, check-out 11am; spa appointments in 60/90-minute blocks.",
      q_menu_requirements: ["breakfast"],
      q_confirmation_mode: "deposit_then_confirm",
    },
  },
  {
    venueName: "Marbella Bay Resort",
    category: "hotel_spa",
    intakeMode: "hybrid",
    answers: {
      q_intake_mode: "hybrid",
      q_inventory_core: "Resort room and suite bookings, poolside cabana rentals, and an on-site spa with massage and facial treatments.",
      q_business_name: "Marbella Bay Resort",
      q_open_days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
      q_operating_hours: "Front desk 24/7; pool and cabanas 8am to 8pm; spa 9am to 6pm.",
      q_table_layout: "120 rooms and suites, 15 poolside cabanas, spa has 6 treatment rooms.",
      q_service_periods: "Check-in 4pm, check-out noon; cabana rentals by half-day or full-day; spa in 50/80-minute blocks.",
      q_menu_requirements: ["breakfast", "lunch", "dinner", "drinks"],
      q_confirmation_mode: "deposit_then_confirm",
    },
  },
  {
    venueName: "Juniper Ridge Lodge",
    category: "hotel_spa",
    intakeMode: "venue_schedule",
    answers: {
      q_intake_mode: "venue_schedule",
      q_inventory_core: "Mountain lodge room bookings with seasonal ski-in/ski-out access, no on-site spa.",
      q_business_name: "Juniper Ridge Lodge",
      q_open_days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
      q_operating_hours: "Front desk 24/7, seasonal operation November through April.",
      q_table_layout: "32 lodge rooms across 4 floors, including 6 family suites with bunk rooms.",
      q_service_periods: "Standard check-in 4pm, check-out 10am during peak season.",
      q_menu_requirements: ["breakfast"],
      q_confirmation_mode: "instant_confirm",
    },
  },
  {
    venueName: "Serene Waters Day Spa",
    category: "hotel_spa",
    intakeMode: "venue_schedule",
    answers: {
      q_intake_mode: "venue_schedule",
      q_inventory_core: "Standalone day spa offering massage, facial, and body treatments booked by treatment room and therapist.",
      q_business_name: "Serene Waters Day Spa",
      q_open_days: ["tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
      q_operating_hours: "Tuesday through Sunday, 9am to 8pm, closed Mondays.",
      q_table_layout: "5 treatment rooms, 1 couples' suite, relaxation lounge for pre/post-treatment guests.",
      q_service_periods: "Appointments in 50/80/110-minute blocks throughout the day.",
      q_menu_requirements: [],
      q_confirmation_mode: "manual_approval",
    },
  },

  // --- Private dining ---
  {
    venueName: "The Cellar Room",
    category: "private_dining",
    intakeMode: "event",
    answers: {
      q_intake_mode: "event",
      q_inventory_core: "Private wine-cellar dining room bookable for full-buyout dinners, 12-24 guests, chef's tasting menu only.",
      q_business_name: "The Cellar Room",
      q_open_days: ["tuesday", "wednesday", "thursday", "friday", "saturday"],
      q_operating_hours: "Tuesday through Saturday, single nightly booking 6:30pm to 10:30pm.",
      q_table_layout: "One long communal table seats 12, extendable configuration seats up to 24 with side tables.",
      q_service_periods: "Single nightly private seating, 6:30pm start, 4-hour block.",
      q_menu_requirements: ["dinner", "drinks"],
      q_confirmation_mode: "deposit_then_confirm",
    },
  },
  {
    venueName: "Magnolia Private Suite",
    category: "private_dining",
    intakeMode: "event",
    answers: {
      q_intake_mode: "event",
      q_inventory_core: "Private dining suite attached to a larger restaurant, bookable for business dinners and small celebrations, 8-16 guests.",
      q_business_name: "Magnolia Private Suite",
      q_open_days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday"],
      q_operating_hours: "Monday through Saturday, lunch and dinner bookings, 11am to 10pm.",
      q_table_layout: "One private room with a single table seating 8, expandable with a leaf to seat 16.",
      q_service_periods: "Lunch bookings 11am-2pm, dinner bookings 5:30pm-10pm.",
      q_menu_requirements: ["lunch", "dinner", "special_event"],
      q_confirmation_mode: "request_to_book",
    },
  },
  {
    venueName: "Ember & Oak Chef's Table",
    category: "private_dining",
    intakeMode: "event",
    answers: {
      q_intake_mode: "event",
      q_inventory_core: "Chef's table experience inside an open kitchen, 6-10 guests, interactive multi-course tasting menu.",
      q_business_name: "Ember & Oak Chef's Table",
      q_open_days: ["thursday", "friday", "saturday"],
      q_operating_hours: "Thursday through Saturday, single seating at 7pm.",
      q_table_layout: "One chef's table seats 10 in a U-shape facing the open kitchen line.",
      q_service_periods: "Single nightly seating, 7pm start, approximately 2.5-hour tasting experience.",
      q_menu_requirements: ["dinner", "drinks"],
      q_confirmation_mode: "deposit_then_confirm",
    },
  },
];

/** Categories represented in the corpus, for quick coverage assertions. */
export function corpusCategories() {
  return [...new Set(SEED_CORPUS.map((record) => record.category))];
}
